#!/bin/bash
set -e

echo "=== Manifold V1 End-to-End Test ==="
echo ""
echo "This test validates the full loop with a real Cowork session."
echo "Run each step manually and verify the expected outcome."
echo ""

echo "PREREQUISITES:"
echo "  - Manifold app built and running (ManifoldApp/build.sh && open the .app)"
echo "  - Claude Desktop installed"
echo "  - Apple Mail running with at least one email account"
echo ""

echo "=== STEP 1: First Launch ==="
echo "Expected: Onboarding wizard appears (3 screens)"
echo "Action: Click through all 3 screens, click 'Get Started'"
echo "Verify: Main window shows Sources view with empty state"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 2: Add File Sources ==="
echo "Expected: Finder picker opens"
echo "Action: Click 'Add files or folders', select a test directory"
echo "Verify: Source appears in list with file count and 'Synced' badge"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 3: Connect Apple Mail ==="
echo "Expected: Switch to Emails tab, click 'Connect Apple Mail'"
echo "Action: Wait for emails to load (may take 30+ seconds)"
echo "Verify: Email list shows with green/yellow status indicators"
echo "Verify: Banking emails show yellow 'Banking' badge"
echo "Verify: 2FA emails show yellow '2FA code' badge"
echo "Verify: Summary bar shows 'N shared, M auto-hidden'"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 4: Check Access Summary ==="
echo "Action: Click 'What Claude sees' in the toolbar"
echo "Verify: Popover shows file count, email count, hidden count"
echo "Verify: Shows 'No active access' when no run is active"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 5: Grant Access ==="
echo "Expected: Guardrail notice appears (first time only)"
echo "Action: Click 'I understand', then 'Grant to Claude' in Activity view"
echo "Verify: Guardrail modal shows boundary notice"
echo "Verify: Finder opens showing the workspace directory"
echo "Verify: Claude Desktop opens (or attempt to open)"
echo "Verify: Toolbar summary updates to 'Cowork access active'"
echo "Verify: Menu bar icon changes from circle to circle.fill"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 6: Agent Modifies Files ==="
echo "Action: In Cowork, ask Claude to modify a file in the workspace"
echo "Verify: Activity timeline shows the modification in real-time"
echo "Verify: If the file is sensitive (.env, .pem), a macOS notification appears"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 7: View Diff ==="
echo "Action: Click on a timeline entry to expand it"
echo "Verify: Inline diff shows with red (removed) and green (added) lines"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 8: Restore ==="
echo "Action: Hover over a timeline entry, click 'Restore'"
echo "Verify: File is restored to previous version"
echo "Verify: A new 'Restored' entry appears in the timeline"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 9: End Access ==="
echo "Action: Click 'End Access' in Activity view"
echo "Verify: Agent status returns to inactive"
echo "Verify: Menu bar icon returns to circle (gray)"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 10: Session Replay ==="
echo "Action: Switch to 'Session Replay' tab in Activity"
echo "Action: Select the run you just completed from the dropdown"
echo "Verify: Shows chronological list of all modifications from that session"
echo ""
read -p "Press Enter when done..."

echo "=== STEP 11: Profile Switch ==="
echo "Action: Go to Profiles view"
echo "Verify: Work, Code, Research presets are shown"
echo "Action: Try to switch profiles (should work when no run is active)"
echo ""
read -p "Press Enter when done..."

echo ""
echo "=== ALL STEPS COMPLETE ==="
echo ""
echo "If all steps passed, Manifold V1 is working end-to-end."
echo ""
echo "Known limitations:"
echo "  - AppleScript email fetching is slow for large mailboxes"
echo "  - Promote diff preview is built but not wired into Activity row yet"
echo "  - Session replay shows data from SnapshotStore, requires completed runs"
echo ""
echo "Run: swift test  (should show 40/40 passing)"
