#!/usr/bin/env python3
"""
build-manifold-mark.py — turn Apple's ellipsis.curlybraces template into
the Manifold mark by replacing the three ellipsis dots with a single
pipe subpath.

Input: custom.ellipsis.curlybraces.svg (the actual SF Symbols.app export
       generated by "Apple Native CoreSVG" — viewBox 0 0 3300 2200, single
       <path> per weight group with 5 subpaths: left bracket, right
       bracket, three dots).

For each weight (Ultralight-S, Regular-S, Black-S):
    - Keep subpath 1 (left bracket — Apple's design)
    - Keep subpath 2 (right bracket — Apple's design)
    - Discard subpaths 3, 4, 5 (the three ellipsis dots)
    - Append a new pipe subpath in the centre

Apple's brackets are already designed to interpolate cleanly across the
three weights, so the result is a properly-variable SF Symbol. The pipe
is identical across all three weights, which is fine for an identity
mark.

Usage:
    python3 brand/build-manifold-mark.py custom.ellipsis.curlybraces.svg \\
        brand/manifold.mark.template.svg
"""

import re
import sys
import xml.etree.ElementTree as ET

SVG_NS = "http://www.w3.org/2000/svg"
SVG = "{" + SVG_NS + "}"


# Pipe geometry (identical across all three weights)
# Coordinates are in the column-local space (after the `matrix(1 0 0 1 X 696)`
# outer translation). y=0 is baseline, y=-70.459 is capline-S.
# We make the pipe slightly taller than cap height so it visually matches
# the bracket extents (Apple's brackets extend ~7 units below baseline and
# ~78 above).
PIPE_PATH = "M68 -76L78 -76L78 7L68 7Z"


def split_subpaths(d_attribute: str) -> list:
    """Split a d-string into a list of subpaths. Each subpath starts with
    M or m and ends just before the next M/m or at the string end."""
    # The regex captures M/m and everything up to the next M/m
    parts = re.findall(r"[Mm][^Mm]*", d_attribute)
    return parts


def replace_dots_with_pipe(d_attribute: str) -> str:
    """Keep the first two subpaths (brackets), drop the rest, append the
    pipe. Returns the new d-attribute string."""
    subpaths = split_subpaths(d_attribute)
    if len(subpaths) < 2:
        raise ValueError(
            f"Path has only {len(subpaths)} subpath(s); need at least 2 "
            f"(left + right bracket). Cannot transform."
        )
    brackets = subpaths[:2]
    return "".join(brackets) + PIPE_PATH


def main(input_path: str, output_path: str) -> int:
    ET.register_namespace("", SVG_NS)
    ET.register_namespace("xlink", "http://www.w3.org/1999/xlink")

    tree = ET.parse(input_path)
    root = tree.getroot()

    # Find <g id="Symbols"> → each <g id="Weight-S"> → its <path>
    symbols_g = None
    for g in root.iter(SVG + "g"):
        if g.get("id") == "Symbols":
            symbols_g = g
            break
    if symbols_g is None:
        print("ERROR: <g id='Symbols'> not found.", file=sys.stderr)
        return 1

    transformed = 0
    for weight_g in symbols_g.findall(SVG + "g"):
        weight_id = weight_g.get("id", "")
        if not weight_id.endswith("-S"):
            continue

        path_elements = weight_g.findall(SVG + "path")
        if not path_elements:
            print(f"WARNING: {weight_id} has no <path>, skipping.", file=sys.stderr)
            continue
        if len(path_elements) > 1:
            print(f"WARNING: {weight_id} has {len(path_elements)} paths, "
                  f"using only the first.", file=sys.stderr)

        path = path_elements[0]
        d_old = path.get("d") or ""
        try:
            d_new = replace_dots_with_pipe(d_old)
        except ValueError as e:
            print(f"ERROR transforming {weight_id}: {e}", file=sys.stderr)
            return 1

        path.set("d", d_new)

        # Verify what we did
        new_subpaths = split_subpaths(d_new)
        print(f"  {weight_id}: {len(split_subpaths(d_old))} subpaths "
              f"→ {len(new_subpaths)} subpaths (2 brackets + 1 pipe)")
        transformed += 1

    if transformed == 0:
        print("ERROR: no weight groups found.", file=sys.stderr)
        return 1

    # Update the descriptive name in Notes
    for text in root.iter(SVG + "text"):
        if text.get("id") == "descriptive-name":
            text.text = "Generated from manifold.mark"
            break

    tree.write(output_path, xml_declaration=True, encoding="utf-8")
    print(f"\n✓ Wrote {output_path}")
    print(f"  Drag this file into SF Symbols.app → Custom Symbols")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(f"usage: {sys.argv[0]} <apple-export.svg> <output.svg>",
              file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1], sys.argv[2]))
